version: '3.5'

services:
  postgis:
    image: postgis/postgis:12-master
    volumes:
      - ./postgis_data:/var/lib/postgresql
    environment:
      ALLOW_IP_RANGE: 0.0.0.0/0
      POSTGRES_PASS: root
      POSTGRES_USER: root
      POSTGRES_DB: postgis
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

  # postgres:
  #   container_name: postgres_container
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     PGDATA: /data/postgres
  #   volumes:
  #     - postgres:/data/postgres
  #     - ./postgres-data:/tmp/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - postgres
  #   restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/root/.pgadmin
      - ./pgadmin-data:/tmp
    ports:
      - "8080:80"
    networks:
      - postgis
    restart: unless-stopped

networks:
  postgis:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    pgadmin-data:
    postgres-data:
    postgis_data: